# Generated by Django 4.1.2 on 2022-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='otp',
            field=models.TextField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='verify',
            name='verified',
            field=models.TextField(default='False'),
        ),
    ]
