# Generated by Django 4.1.1 on 2022-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verify_otp_verify_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='otp',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verify',
            name='verified',
            field=models.TextField(default=False),
        ),
    ]
